<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    async function foo() {
        // await右侧是非promise的值，则直接返回这个值
        // const res2 = await 1

        //如果右侧是promise对象，则返回的是promise成功的值
        const res2 = await Promise.resolve(111)
        console.log(res2)


        try {
            // 如果是失败的promise，则通过try catch进行捕获
            const res3 = await Promise.reject(3333)

            // 这种写不了
            // const res3 = await throw new Error(12333)
            console.log(res3)
        } catch (e) {
            console.log(e)
        }
        // return res2
    }

    const result = foo()


    async function bar() {
        console.log(1)
        const res1 = await 123;
        console.log(2)
        const res2 = await 456;
        console.log(3)
        const res3 = await 789;
        console.log(4)
    }

    console.log(4)
    bar()
    console.log(5)

    //4 1 5 2 3 4


    // console.log(result)

</script>
</body>
</html>